language: python
dist: xenial

python:
  - 2.7  # should download/install v3.5.2
  - 3.5
  - 3.6
  - 3.7
  - 3.8

addons:
  apt_packages:
    - libbz2-dev
    - libhdf5-serial-dev
    - liblzo2-dev

before_install:
  - pip install numpy numexpr  # install requirements from regural PyPI

install:
  - pip install --no-binary=tables tables
  - pip download --only-binary=tables --no-deps tables
  - ls

script:
  - cd .. && python -m tables.tests.test_all
  - pt2to3 -h
  - ptrepack -h
  - ptdump -h
  - pttree -h
